// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBG6tHdSFE7fcWG4f8YJDr7sr8E5ZWGS1E',
    appId: '1:560785961911:web:1fa7dbfda7dcaf36bcae32',
    messagingSenderId: '560785961911',
    projectId: 'foundit-f312d',
    authDomain: 'foundit-f312d.firebaseapp.com',
    storageBucket: 'foundit-f312d.firebasestorage.app',
    measurementId: 'G-DSXSP4BBMM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsI0ft-M2AglmEqHdUI9vwMK3ncsXjhCk',
    appId: '1:560785961911:android:37d54ce8dfe15ad9bcae32',
    messagingSenderId: '560785961911',
    projectId: 'foundit-f312d',
    storageBucket: 'foundit-f312d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmoNO7VaYni19gUqIrcUlKiacexOcnBTM',
    appId: '1:560785961911:ios:5a375543098eb8a2bcae32',
    messagingSenderId: '560785961911',
    projectId: 'foundit-f312d',
    storageBucket: 'foundit-f312d.firebasestorage.app',
    iosBundleId: 'com.example.yallaAdminPanel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmoNO7VaYni19gUqIrcUlKiacexOcnBTM',
    appId: '1:560785961911:ios:5a375543098eb8a2bcae32',
    messagingSenderId: '560785961911',
    projectId: 'foundit-f312d',
    storageBucket: 'foundit-f312d.firebasestorage.app',
    iosBundleId: 'com.example.yallaAdminPanel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBG6tHdSFE7fcWG4f8YJDr7sr8E5ZWGS1E',
    appId: '1:560785961911:web:628f595528b4407bbcae32',
    messagingSenderId: '560785961911',
    projectId: 'foundit-f312d',
    authDomain: 'foundit-f312d.firebaseapp.com',
    storageBucket: 'foundit-f312d.firebasestorage.app',
    measurementId: 'G-BYSQSW5PLJ',
  );

}